### ISSUE TITLE
linuxでもHVC-P2が使えますか。

### ISSUE THREAD

**Issue by outan** [futomi/node-omron-hvc-p2#2]
店舗内で来店客の情報を収集し、販売提案できるソリューションを考えています。
Linux(raspberry pi)で開発したいですが、
下記のページではWindowsのusb driverしか提供されていないようです。
https://www.omron.co.jp/ecb/products/mobile/hvc_p2/

https://github.com/futomi/node-omron-hvc-p2#dependencies
⇒macとLinuxではusb driverなくても開発できるのでしょうか。
必要であれば、どこから取得できるのでしょうか。

よろしくお願いいたします。

**Comment by outan** [comment]
こちらのcommitによって、linux(raspberry pi)でもHVC-PCが使えるということが確認できました。
どうもありがとうございました。

**Comment by awarimosh** [comment]
How did you go about making it work on Linux ???

**Comment by futomi** [comment]
This module works well on Linux such as Raspbian, Ubuntu, etc.
