### ISSUE TITLE
Device not found, caused by productId.

### ISSUE THREAD

**Issue by ecbatana** [futomi/node-omron-hvc-p2#3]
Recently i was tried using example code, then the code return `Error: No device was found.`. Im using HVC P2 device.
Im curious about this error, then i looked into the source code in HvcP2.js. What i got is this error caused by difference between my HVC P2 device productId and the productId in HvcP2.js.

This is the output of _dmesg_ log of detected HVC P2 device.

`[ 1526.436368] usb 1-1: new full-speed USB device number 5 using xhci_hcd`
`[ 1526.565727] usb 1-1: New USB device found, idVendor=0590, idProduct=00ca`
`[ 1526.565731] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3`
`[ 1526.565733] usb 1-1: Product: OMRON HVC-P2`
`[ 1526.565735] usb 1-1: Manufacturer: OMRON Corporation`
`[ 1526.565736] usb 1-1: SerialNumber: 1`

In HvcP2.js source code, in linux section the productId is **OMRON HVC-P2** _(im using linux)_, when my detected HVC P2 device productId is **00ca**.

This is what i seen in HvcP2.js source code.

`} else if(pf === 'linux') {`
`                // ------------------------------------------------`
`                // * linux`
`                // {`
`                //   "manufacturer": "OMRON Corporation",`
`                //   "serialNumber": "1",`
`                //   "pnpId": "usb-OMRON_Corporation_OMRON_HVC-P2_1-if00",`
`                //   "vendorId": "0590",`
`                //   "productId": "OMRON HVC-P2",`
`                //   "comName": "/dev/ttyACM0"`
`                // }`
`                // ------------------------------------------------`
`                com_list.forEach((com) => {`
`                    if(com.manufacturer && com.manufacturer.match(/OMRON/, 'i') && com.vendorId && com.vendorId.match(/0590/) && com.productId && com.productId.match(/HVC\-P2/, 'i')) {`
`                        candidate_com_list.push(com);`
`                    }`
`                });`
`}`

When i manually delete this line `&& com.productId.match(/HVC\-P2/, 'i')` in HvcP2.js, my script work fine, returning detection result.

Which one is the right productId? **OMRON HVC-P2** or my **00ca**, because i've seen in HvcP2.js source code, other platform such as windows and osx _(darwin)_ productId is **00ca**.

**Comment by futomi** [comment]
Thank you so match for your feedback.

I had tested this module on Ubuntu and Raspbian, it had worked well.
Reading your feedback, I tried it on Fedora. I confirmed that the auto-detection failed on Fedora.
As you pointed, the `productId` was set to `00ca`.

I updated this module and published it on github and npm. Try the latest version.

Cheers.

**Comment by ecbatana** [comment]
Happy to hear that, thanks.
